Repository diegolnasc/gotcha, pull requests merged in 2021-12, with the labels that each got.

#4 fix: change if in process check run event
  pkg/github/worker.go
Labels: bug, good first issue

#5 fix: pullrequest nil in issue comment
  pkg/github/controller.go
  pkg/github/issue.go
  pkg/github/pull_request.go
  pkg/github/worker.go
Labels: bug

#6 feat: merge implementation
  Dockerfile
  README.md
  build/config.yaml
  pkg/config/config.go
  pkg/github/controller.go
  pkg/github/issue.go
  pkg/github/worker.go
Labels: documentation, enhancement

#10 feat: release
  .github/workflows/release-please.yml
  README.md
  build/config.yaml
Labels: enhancement

#14 docs: update readme and contributing
  CONTRIBUTING.md
  README.md
  docs/imgs/install-1.png
  docs/imgs/install-2.png
  docs/imgs/pr-name-pattern-fail.png
  docs/imgs/pr-name-pattern-pass.png
  docs/imgs/pr-overview.png
Labels: documentation

#7 feat: update go version to 1.17
  go.mod
Labels: enhancement

#9 refactor: service and structure + pull request overview
  build/config.yaml
  cmd/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/github/check.go
  pkg/github/common.go
  pkg/github/controller.go
  pkg/github/github.go
  pkg/github/handler.go
  pkg/github/issue.go
  pkg/github/pull_request.go
  pkg/github/worker.go
Labels: documentation, enhancement

#15 docs: project documentation
  README.md
  cmd/main.go
  pkg/config/config.go
  pkg/github/check.go
  pkg/github/common.go
  pkg/github/github.go
  pkg/github/handler.go
  pkg/github/issue.go
  pkg/github/pull_request.go
  pkg/github/worker.go
Labels: documentation

#16 feat: lint workflow
  cmd/main.go
  pkg/config/config.go
  pkg/github/check.go
  pkg/github/common.go
  pkg/github/github.go
  pkg/github/handler.go
  pkg/github/issue.go
  pkg/github/pull_request.go
  pkg/github/worker.go
Labels: documentation
